### ISSUE TITLE
Lab2 website-lab2.sh issue replacing the API Gateway URL

### ISSUE THREAD

**Issue by vbontoux** [aws-samples/aws-saas-factory-serverless-workshop#43] opened 2022-09-07 14:32 UTC
Tried to start Lab2 again and found that there is an issue on step 2 :
The sed command in website-lab2.sh does not properly replace the API Gateway URL in the `client/src/shared/config.jsfile`.
There are no visible errors appart that later the call from the React Client to the REST API fails while trying to call the register URL `/v1/registration`
After fixing this issue and redeploying the React Client with website-lab2.sh I fall into another trap : the registration Lambda is returning an error :
`Cannot register new tenant. Hot pool of RDS clusters has been depleted.`

**Comment by brtrvn** [comment] 2022-09-13 19:39
@vbontoux I was unable to reproduce your specific errors, however I wasn't able to provision the workshop at all because Aurora has deprecated version 10 for Postgres. Once I updated the Aurora Postgres version to a more recent release, the workshop provisioned properly and I had no issues with CORS or with the `sed` command.

I did see an error from NPM that the version of ansi-html-community was not valid. Removing the generated package-lock.json file and rerunning the website script resolved those issues.

I've committed those changes. Do a fresh `git pull` from `main` and let us know if you continue to see problems. It is _very important_ to follow the lab instructions carefully. You must be sure to wait for the lab CloudFormation stacks to _completely_ finish before running the website scripts.

**Comment by vbontoux** [comment] 2022-10-11 09:23
Many thanks ! I will refresh and try again !Vincent
    
  

 From: brtrvn ***@***.***>Sent: Tuesday, September 13, 2022 21:39To: aws-samples/aws-saas-factory-serverless-workshop ***@***.***>Cc: Vincent Bontoux ***@***.***>; Mention ***@***.***>Subject: Re: [aws-samples/aws-saas-factory-serverless-workshop] Lab2 website-lab2.sh issue replacing the API Gateway URL (Issue #43) 
@vbontoux I was unable to reproduce your specific errors, however I wasn't able to provision the workshop at all because Aurora has deprecated version 10 for Postgres. Once I updated the Aurora Postgres version to a more recent release, the workshop provisioned properly and I had no issues with CORS or with the sed command.
I did see an error from NPM that the version of ansi-html-community was not valid. Removing the generated package-lock.json file and rerunning the website script resolved those issues.
I've committed those changes. Do a fresh git pull from main and let us know if you continue to see problems. It is very important to follow the lab instructions carefully. You must be sure to wait for the lab CloudFormation stacks to completely finish before running the website scripts.

**Comment by brtrvn** [comment] 2022-11-17 01:05
Closing due to no activity

**Closed by brtrvn** 2022-11-17 01:05 UTC
